### ISSUE TITLE
How is this licensed?

### ISSUE THREAD

**Issue by emlun** [jhob/tmux-profile#1]
Would you mind adding some kind of license/unlicense notice to the repository?

**Comment by emlun** [comment]
For the record, just in case it might help: http://choosealicense.com/

**Comment by jhob** [comment]
Hey @emlun. I just committed the MIT license file. Thanks for checking out tmux-profile!

**Comment by emlun** [comment]
Thank _you_ for writing it! I've started my own fork of it too. :)
